"""Update table: items (make optional)

Revision ID: d4bd7034aa64
Revises: 3049af05dc62
Create Date: 2025-06-18 23:51:57.615407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd4bd7034aa64'
down_revision: Union[str, None] = '3049af05dc62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('item', 'limit',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('item', 'lowalch',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index('ix_price_item_id', table_name='price')
    op.create_index(op.f('ix_price_item_id'), 'price', ['item_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_price_item_id'), table_name='price')
    op.create_index('ix_price_item_id', 'price', ['item_id'], unique=False)
    op.alter_column('item', 'lowalch',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('item', 'limit',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
