"""Update table: items (make optional)

Revision ID: 658c51549836
Revises: d4bd7034aa64
Create Date: 2025-06-18 23:52:45.162935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '658c51549836'
down_revision: Union[str, None] = 'd4bd7034aa64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('item', 'highalch',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('item', 'highalch',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
