"""Add table: price

Revision ID: 3fb15ed93f05
Revises: 658c51549836
Create Date: 2025-06-19 00:29:37.779372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3fb15ed93f05'
down_revision: Union[str, None] = '658c51549836'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('price', 'high',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('price', 'high',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
