"""Add table: price

Revision ID: 1532a3d1ffd4
Revises: 3fb15ed93f05
Create Date: 2025-06-19 00:30:04.722714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1532a3d1ffd4'
down_revision: Union[str, None] = '3fb15ed93f05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('price', 'high_time',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('price', 'high_time',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
