"""Add table: price

Revision ID: 9b5e6113814b
Revises: 1532a3d1ffd4
Create Date: 2025-06-19 00:30:22.336932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9b5e6113814b'
down_revision: Union[str, None] = '1532a3d1ffd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('price', 'low',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('price', 'low_time',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('price', 'low_time',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('price', 'low',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
