version: "3.9"

services:
  backend:
    build:
      context: ./api
    container_name: runescape-api
    restart: always
    ports:
      - "8000:8080" # Host:Container
    depends_on:
      - db
    networks:
      - runescape-net
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: runescape

  frontend:
    build:
      context: ./web
    container_name: runescape-web
    restart: always
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_V1_BASE_URL: http://localhost:8000/api/v1
      NEXT_PUBLIC_WS_V1_BASE_URL: ws://localhost:8000/api/v1
    depends_on:
      - backend
    networks:
      - runescape-net

  db:
    image: postgres:15
    container_name: runescape-db
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: runescape
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - runescape-net

volumes:
  pgdata:

networks:
  runescape-net:
    driver: bridge
